/**
 * Generates thermal-printer-compatible QC label data (ZPL string or HTML preview).
 * Designed for 4"×6" (101.6mm × 152.4mm) label stock at 203 DPI.
 */

export interface QCLabelData {
  lotNumber: string
  sku: string
  productName: string
  batchNumber: string
  quantity: number
  result: string          // Pass | Fail | Pass with Conditions | etc.
  inspectorEmail: string
  inspectionDate: string  // YYYY-MM-DD
  companyName?: string
}

const RESULT_SYMBOL: Record<string, string> = {
  Pass: '✓ PASS',
  'Pass with Conditions': '~ PASS W/ CONDITIONS',
  Fail: '✗ FAIL',
  'Rework Required': '⚑ REWORK REQUIRED',
  Pending: '○ PENDING',
}

/**
 * Returns a ZPL II label string ready to send to a Zebra thermal printer.
 */
export function generateQCLabelZPL(data: QCLabelData): string {
  const result = RESULT_SYMBOL[data.result] ?? data.result
  const company = data.companyName ?? 'beyondGREEN'
  const date = data.inspectionDate
  const inspector = data.inspectorEmail.split('@')[0].toUpperCase()

  return [
    '^XA',
    '^CF0,30',
    `^FO50,30^FD${company}^FS`,
    '^CF0,25',
    `^FO50,70^FDQUALITY CONTROL LABEL^FS`,
    '^FO40,100^GB720,3,3^FS',
    '^CF0,35',
    `^FO50,115^FDSKU: ${data.sku}^FS`,
    '^CF0,28',
    `^FO50,160^FD${data.productName.slice(0, 40)}^FS`,
    `^FO50,200^FDLOT: ${data.lotNumber}^FS`,
    `^FO50,235^FDBATCH: ${data.batchNumber}^FS`,
    `^FO50,270^FDQTY: ${data.quantity}^FS`,
    '^FO40,300^GB720,3,3^FS',
    '^CF0,40',
    `^FO50,315^FD${result}^FS`,
    '^FO40,365^GB720,3,3^FS',
    '^CF0,22',
    `^FO50,380^FDINSPECTOR: ${inspector}^FS`,
    `^FO50,410^FDDATE: ${date}^FS`,
    `^FO400,380^BQN,2,5^FDQA,${data.lotNumber}^FS`,
    '^XZ',
  ].join('\n')
}

/**
 * Returns an HTML string for browser-based label preview.
 */
export function generateQCLabelHTML(data: QCLabelData): string {
  const result = data.result
  const resultColor = result === 'Pass'
    ? '#00C896'
    : result === 'Fail'
    ? '#ef4444'
    : result === 'Pass with Conditions'
    ? '#f59e0b'
    : '#9898A8'
  const company = data.companyName ?? 'beyondGREEN'
  const inspector = data.inspectorEmail.split('@')[0]

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { margin: 0; padding: 0; font-family: 'Courier New', monospace; }
  .label {
    width: 384px; height: 576px;
    border: 2px solid #ccc;
    padding: 16px;
    background: #fff;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .company { font-size: 18px; font-weight: bold; color: #111; }
  .title { font-size: 12px; color: #666; letter-spacing: 1px; }
  hr { border: none; border-top: 2px solid #111; margin: 4px 0; }
  .sku { font-size: 22px; font-weight: bold; color: #111; }
  .field { font-size: 13px; color: #333; }
  .result {
    font-size: 20px; font-weight: bold;
    color: ${resultColor};
    border: 2px solid ${resultColor};
    padding: 4px 12px;
    border-radius: 4px;
    display: inline-block;
    margin: 4px 0;
  }
  .footer { margin-top: auto; font-size: 11px; color: #666; }
</style>
</head>
<body>
<div class="label">
  <div class="company">${company}</div>
  <div class="title">QUALITY CONTROL LABEL</div>
  <hr />
  <div class="sku">${data.sku}</div>
  <div class="field">${data.productName}</div>
  <div class="field">LOT: <strong>${data.lotNumber}</strong></div>
  <div class="field">BATCH: ${data.batchNumber}</div>
  <div class="field">QTY: ${data.quantity.toLocaleString()}</div>
  <hr />
  <div class="result">${RESULT_SYMBOL[result] ?? result}</div>
  <hr />
  <div class="footer">
    <div>Inspector: ${inspector}</div>
    <div>Date: ${data.inspectionDate}</div>
    <div>Generated by beyondGREEN ERP</div>
  </div>
</div>
</body>
</html>`
}

/**
 * Triggers a browser print dialog for the label HTML.
 */
export function printQCLabel(data: QCLabelData): void {
  const html = generateQCLabelHTML(data)
  const win = window.open('', '_blank', 'width=450,height=650')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  win.print()
}
